name: Bing img chatcher
on: 
  schedule:
    - cron: 00 03 * * *
  push:
jobs:
  runer:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup jq
        run: |
          sudo apt install jq
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: body
        env:
          key: ${{ secrets.Actions_Key }}
        run: |
          echo $key
          mkdir -p ~/.ssh/
          echo "$key" | tr -d '\r' > ~/.ssh/id_rsa # Set private key
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'Action Pusher' 
          git config --global user.email 'action@github.com'
          get=`curl "https://bing.com/HPImageArchive.aspx?format=js&idx=0&n=1"|jq ".images[].url"`
          prefix="https://bing.com"
          echo $prefix$get
          # curl $prefix$get >read.png
          git add .
          git commit -m "Auto Commit"
          
          
